networks:
  nginx-proxy:
    external: false

volumes:
  certs:
  vhost:
  html:
  acme:

services:
  api:
    image: ghcr.io/lambdaateam/emenu/api:main
    container_name: emenu-api
    restart: always
    networks:
      - nginx-proxy
    depends_on:
      - letsencrypt
      - proxy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - VIRTUAL_HOST=api.emenu.psykka.xyz
      - LETSENCRYPT_HOST=api.emenu.psykka.xyz
      - ENV=production

  # ws:
  #   image: ghcr.io/lambdaateam/emenu/ws:main
  #   container_name: emenu-ws
  #   restart: always
  #   depends_on:
  #     - letsencrypt
  #     - proxy
  #   networks:
  #     - nginx-proxy
  #   environment:
  #     - VIRTUAL_HOST=ws.emenu.psykka.xyz
  #     - LETSENCRYPT_HOST=ws.emenu.psykka.xyz
  #     - ENV=production

  short:
    image: ghcr.io/lambdaateam/emenu/shortener:main
    container_name: emenu-short
    restart: always
    depends_on:
      - letsencrypt
      - proxy
    networks:
      - nginx-proxy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - VIRTUAL_HOST=short.emenu.psykka.xyz
      - LETSENCRYPT_HOST=short.emenu.psykka.xyz
      - ENV=production
  
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: emenu-proxy
    restart: always
    networks:
      - nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: emenu-letsencrypt
    restart: always
    networks:
      - nginx-proxy
    depends_on:
      - proxy
    environment:
      - DEFAULT_EMAIL=emenu@psykka.xyz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
